# Array creation routines

In [1]:
import numpy as np

## Question
Create a new array of 2*2 integers, without initializing entries.

In [2]:
np.empty((2,2), dtype=np.int64)

array([[ 2305843009213693952, -6917520263142721713],
       [                   4,                    0]])

## Question
Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [3]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
np.empty_like(X)

array([[         0, 1074266112,          0],
       [1073741824,          0, 1072693248]], dtype=int32)

## Question
Create an array with ones on the diagonal and zeros elsewhere.

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Question
Create a new array of 3*2 float numbers, filled with ones.

In [5]:
np.ones((3,2), dtype=np.float64)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Question
Create a new array of 2*5 uints, filled with 6.

In [6]:
np.full((2,5), 6, dtype=np.uint32)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

## Question
Create an array of 2, 4, 6, 8, ..., 100.

In [7]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

## Question
Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [8]:
np.linspace(3., 10., 50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

## Question
Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [9]:
X = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
np.diagonal(X)

array([ 0,  5, 10])

## Question
Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [10]:
np.diagflat([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Indexing and slicing

## Question
Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
Using indexing, select all the elements of the first column

In [11]:
X = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(X)
print(X[np.arange(3), np.array([0])])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 4 8]


## Question
Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                  [ 8,  9, 10, 11],
                  [ 12,13, 14, 15]]).
Using indexing, select all the elements of the diagonal

In [12]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11], [ 12,13, 14, 15]])
print(X)
print(X[np.arange(4), np.arange(4)])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]


## Question
Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                  [ 8,  9, 10, 11],
                  [ 12,13, 14, 15]]).
Using indexing, select the third row

In [13]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11], [ 12,13, 14, 15]])
print(X)
print(X[np.array([2]), np.arange(4)])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 8  9 10 11]


## Question
Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                  [ 8,  9, 10, 11],
                  [ 12,13, 14, 15]]).
Using slicing, select the third row

In [14]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11], [ 12,13, 14, 15]])
print(X)
print(X[2:3,:])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9 10 11]]


## Question
Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                  [ 8,  9, 10, 11],
                  [ 12,13, 14, 15]]).
Using boolean indexing, select all the even numbers and set them to -1.

In [27]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11], [ 12, 13, 14, 15]])
X[X % 2 == 0] = -1
print(X)

[[-1  1 -1  3]
 [-1  5 -1  7]
 [-1  9 -1 11]
 [-1 13 -1 15]]


## Question
Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                  [ 8,  9, 10, 11],
                  [ 12,13, 14, 15]]).
Using slicing, set the elements of the 2nd row to 0

In [28]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11], [ 12, 13, 14, 15]])
X[1:2, :] = 0
print(X)

[[ 0  1  2  3]
 [ 0  0  0  0]
 [ 8  9 10 11]
 [12 13 14 15]]


# Array manipulation routines

In [16]:
import numpy as np

## Question
Let x be a ndarray with shape (4, 4, 3) with all elements set to zero. Reshape x so that the size of the second dimension equals 12. Use reshape().

In [17]:
x = np.zeros((4, 4, 3))
out = x.reshape((4, 12))
print(out)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Question
Let x = np.array([[1, 2, 3], [4, 5, 6]]). Convert it to [1 4 2 5 3 6]. Use ravel().

In [18]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

## Question
Let x = np.array([[1, 2, 3], [4, 5, 6]]). Get the 5th element.

In [19]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)[4]

5

## Question
Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5). Use swapaxes().

In [20]:
x = np.zeros((3, 4, 5))
x = np.swapaxes(x, 1, 0)
print(x.shape)

(4, 3, 5)


## Question
Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4). Use expand_dims().

In [21]:
x = np.zeros((3, 4))
x = np.expand_dims(x, axis=1)
print(x.shape)

(3, 1, 4)


## Question
Let x be an arbitrary 3-D array of shape (3, 1, 4). Remove a single-dimensional entries such that the new shape will be (3, 4). Use squeeze().

In [22]:
x = np.zeros((3, 1, 4))
x = np.squeeze(x)
print(x.shape)

(3, 4)


## Question 
Let x = np.array([[1, 2, 3], [4, 5, 6]]) and y = np.array([[7, 8, 9], [10, 11, 12]]). Concatenate x and y so that a new array looks like np.array([[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]). Use concatenate().

In [23]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate((x, y), 1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Question 
Let x = np.array([[1, 2, 3], [4, 5, 6]]) and y = np.array([[7, 8, 9], [10, 11, 12]]). Concatenate x and y so that a new array looks like np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]). Use concatenate().

In [24]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate((x, y), 0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Question 
Let x = np.array([1, 2, 3]). Create a new array like np.array([[1, 2, 3, 1, 2, 3], [1, 2, 3, 1, 2, 3]]). Use tile().

In [26]:
x = np.array([1, 2, 3])
print(np.tile(x, (2, 2)))

[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]
